[project]
name = "fastapi-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14.7"
dependencies = [
    "alembic>=1.19.2",
    "fastapi[standard]>=0.141.1",
    "httpx>=0.28.1",
    "pwdlib[argon2]>=0.3.1",
    "pyjwt>=2.14.0",
    "pymysql>=1.2.0",
    "sqlalchemy>=2.0.52",
    "sqlmodel>=0.0.42",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]

[project.scripts]
fastapi-project = "app:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
